### ISSUE TITLE
Enhance Project with Required React Components

### ISSUE THREAD

**Issue by jdregalario-stacktrek** [hammedTiamiyu/stacktrek-website-clone#1]
Currently, your clone app is lacking the essential React components needed to fulfill the activity requirements. As per the guidelines, we are expected to have a minimum of 5 React components integrated into the project.

**_Action Item:_**

- [ ] Create three more components in your clone app.

**Comment by jdregalario-stacktrek** [comment]
@hammedTiamiyu

**Comment by hammedTiamiyu** [comment]
Fixed. Thanks
